### ISSUE TITLE
Parent account crashing 

### ISSUE THREAD

**Issue by xdk78** [shymmq/librus-client#104]
Crashing on 83%

**Comment by tomikmar** [comment]
I have similar problem. Crashing about 81%.

Version 1.0r

**Comment by Frioo** [comment]
I'm using a parent account exclusively and I have never experienced a single crash while downloading.
Possibly another JSON problem (missing tokens etc.)

**Comment by shymmq** [comment]
@xdk78 @tomikmar Do the student accounts work properly?

**Comment by tomikmar** [comment]
I don't have student account. 

BTW. I use F-Droid build on LineageOS 14.1

**Comment by mimi89999** [comment]
I am using the same build from F-Droid, also on LOS 14.1 and I don't experience any issues with a students account.

**Comment by tomikmar** [comment]
Strange - it started to work, but I only have access to "Plan lekcji". It may be related to the current server maintenance (log attached).
[librus-2017-03-17.txt](https://github.com/shymmq/librus-client/files/851924/librus-2017-03-17.txt)

**Comment by shymmq** [comment]
Can you try to log in using the following credentials?
username: 13335
password: librus11

**Comment by tomikmar** [comment]
After the maintenance the app started to crash again.

I cleared app data and I tried user 13335. Everything works correctly with this user.

**Comment by tomikmar** [comment]
Crash log: 
[librus-2017-03-18.txt](https://github.com/shymmq/librus-client/files/852239/librus-2017-03-18.txt)

**Comment by shymmq** [comment]
```
pl.librus.client.api.HttpException: 
{
"Status":"Error",
"Code":"LuckyNumberIsNotActive",
"Message":"Lucky number is not active.",
}
```
This is causing the crash. I'll try to fix it soon.

**Comment by mimi89999** [comment]
@tomikmar I will PR to F-Droid this evening.
