### ISSUE TITLE
Skąd wziąłeś adresy URL do RESTowego API Librusa?

### ISSUE THREAD

**Issue by matisiekpl** [shymmq/librus-client#125]
Skąd wziąłeś adresy URL do RESTowego API Librusa?
Po prostu jestem ciekaw? Debuggowałeś web clienta? Rozebrałeś obecną apkę

**Comment by Frioo** [comment]
Przechwytywanie pakietów z oficjalnej aplikacji.
Poza tym adresy można wykopać ze zdekompilowanego pliku apk.

**Comment by MatisiekPL** [comment]
Ok. Dzięki. Może to duża prośba, ale fajnie by było jakbyś rozpisał to w jakiejś dockumentacji open-source
