### ISSUE TITLE
Zle pobiera info o sprawdzianie

### ISSUE THREAD

**Issue by Bartixxx32** [shymmq/librus-client#24]
Witaj znalzlem blad zle jest pobierana informacja o spraedzianie (nauczyciela) bo ona bierze nazwe nauczyciela na lekcji 1 bo np w naszej szkole wszystkie spraedziany sa wpisane na 1 a nie na ktoras tam dokladnie synergia pobiera dibrze nauczyciela lecz twoj dziennik jak pisalem bierze go z lekcji na jaka jest wpisany

**Comment by shymmq** [comment]
Naprawione w 7ab484d946036bbf7591280407292b74b924e7a0.

![](https://dl2.pushbulletusercontent.com/QmDmAeMi7QeFJRvcIhEx2Lje7C5GXGBU/Screenshot_20161212-153540.png)

**Comment by xdk78** [comment]
Po zalogowaniu, nie wiem czemu ale nawet na nexus 5(VM) nie działa, tak samo na moim p8 lite po full wipe w twrp https://github.com/shymmq/librus-client/commit/7ab484d946036bbf7591280407292b74b924e7a0 
http://imgur.com/a/cdsZn
Nie wiem, może moje konto na librusie jest pierdolnięte :D

**Comment by shymmq** [comment]
Hmm, kilka razy dostałem podobny błąd, jednak zawsze jeśli wyszedłem z aplikacji i znowu wszedłem działało. Pracuję nad tym.

**Comment by xdk78** [comment]
Dzięki, zależy mi żeby to działało bo sam chce troche pomóc.

**Comment by shymmq** [comment]
Czy w logcacie pokazują się jakieś errory/warningi?

**Comment by xdk78** [comment]
Właśnie nie bardzo

**Comment by shymmq** [comment]
Czy mógłbyś podesłać wszystkie logi z tagiem `librus-client-log` ? (jeśli są)

**Comment by xdk78** [comment]
tylko tyle, apke zainstalowałem od nowa i się zalogowałem
`12-12 18:20:06.992 1957-1957/pl.librus.client I/FA: App measurement is starting up, version: 10084
12-12 18:20:06.992 1957-1957/pl.librus.client I/FA: To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
12-12 18:20:07.011 1957-1957/pl.librus.client I/FA: To enable faster debug mode event logging run:
                                                      adb shell setprop debug.firebase.analytics.app pl.librus.client
12-12 18:20:17.833 1957-2981/pl.librus.client I/FA: Tag Manager is not found and thus will not be used`

**Comment by shymmq** [comment]
Strasznie dziwne, odpaliłem właśnie aplikację na VM i wszystko działa poprawnie.

**Comment by Bartixxx32** [comment]
Pewnie coś z kontem tak wooglule shymmq masz moze aplikacje telegram czy cos? ja z xdk78 jestesmy na nim i dyskutujemy na temat tej aplikacji co i jak moze chcial bys dolaczyc czy cos jaki szybki sposob komunikacji?

**Comment by shymmq** [comment]
Dla mnie @Frioo najlepiej by było na discord - https://discord.gg/9hdPQTE ew. hangouts albo telegram

**Comment by Bartixxx32** [comment]
dodasz na telegramie ? 782290727

**Comment by Bartixxx32** [comment]
albo Bartixxx

**Comment by Bartixxx32** [comment]
na discord zaproszenie nieprawidlowe xD

**Comment by Frioo** [comment]
@Bartixxx32 https://discord.gg/r6Ugyk2

**Comment by xdk78** [comment]
@xdk78
