### ISSUE TITLE
Blank screen after login

### ISSUE THREAD

**Issue by shymmq** [shymmq/librus-client#25]

**Comment by xdk78** [comment]
When try login
`12-14 16:35:10.979 17489-19286/pl.librus.client W/System.err: java.net.SocketTimeoutException: timeout
12-14 16:35:10.980 17489-19286/pl.librus.client W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
12-14 16:35:10.980 17489-19286/pl.librus.client W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
12-14 16:35:10.980 17489-19286/pl.librus.client W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
12-14 16:35:10.980 17489-19286/pl.librus.client W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
12-14 16:35:10.980 17489-19286/pl.librus.client W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
12-14 16:35:10.981 17489-19286/pl.librus.client W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
12-14 16:35:10.981 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
12-14 16:35:10.981 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
12-14 16:35:10.981 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
12-14 16:35:10.981 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
12-14 16:35:10.982 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
12-14 16:35:10.982 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
12-14 16:35:10.982 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:287)
12-14 16:35:10.982 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
12-14 16:35:10.982 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12-14 16:35:10.983 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.access$100(Call.java:35)
12-14 16:35:10.983 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
12-14 16:35:10.983 17489-19286/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
12-14 16:35:10.983 17489-19286/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 16:35:10.983 17489-19286/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 16:35:10.983 17489-19286/pl.librus.client W/System.err:     at java.lang.Thread.run(Thread.java:833)
12-14 16:35:11.081 17489-19293/pl.librus.client I/System: core_booster, getBoosterConfig = false
12-14 16:35:11.106 17489-19287/pl.librus.client W/System.err: java.net.SocketTimeoutException: failed to connect to api.librus.pl/46.248.183.10 (port 443) after 10000ms
12-14 16:35:11.106 17489-19287/pl.librus.client W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at java.net.Socket.connect(Socket.java:938)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:230)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:286)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.access$100(Call.java:35)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 16:35:11.107 17489-19287/pl.librus.client W/System.err:     at java.lang.Thread.run(Thread.java:833)
12-14 16:35:11.136 17489-19291/pl.librus.client W/System.err: java.net.SocketTimeoutException: failed to connect to api.librus.pl/46.248.183.10 (port 443) after 10000ms
12-14 16:35:11.136 17489-19296/pl.librus.client W/System.err: java.net.SocketTimeoutException: failed to connect to api.librus.pl/46.248.183.10 (port 443) after 10000ms
12-14 16:35:11.136 17489-19291/pl.librus.client W/System.err:     at 	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
12-14 16:35:11.136 17489-19296/pl.librus.client W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at java.net.Socket.connect(Socket.java:938)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:230)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:286)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at java.net.Socket.connect(Socket.java:938)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.access$100(Call.java:35)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:230)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err: com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
12-14 16:35:11.137 17489-19296/pl.librus.client W/System.err:     at java.lang.Thread.run(Thread.java:833)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err: com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:286)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12-14 16:35:11.137 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.access$100(Call.java:35)
12-14 16:35:11.138 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
12-14 16:35:11.138 17489-19291/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
12-14 16:35:11.138 17489-19291/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 16:35:11.138 17489-19291/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 16:35:11.138 17489-19291/pl.librus.client W/System.err:     at java.lang.Thread.run(Thread.java:833)
12-14 16:35:11.140 17489-19287/pl.librus.client I/System: core_booster, getBoosterConfig = false
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err: java.net.SocketTimeoutException: failed to connect to api.librus.pl/46.248.183.10 (port 443) after 10000ms
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err:     at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err:     at libcore.io.IoBridge.connect(IoBridge.java:122)
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err:     at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err:     at java.net.Socket.connect(Socket.java:938)
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:230)
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:141)
12-14 16:35:11.156 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:286)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.access$100(Call.java:35)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 16:35:11.157 17489-19298/pl.librus.client W/System.err:     at java.lang.Thread.run(Thread.java:833)
12-14 16:35:11.606 17489-19293/pl.librus.client I/System: core_booster, getBoosterConfig = false
12-14 16:35:11.608 17489-19287/pl.librus.client I/System: core_booster, getBoosterConfig = false
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err: java.net.SocketTimeoutException: timeout
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:287)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.access$100(Call.java:35)
12-14 16:35:18.438 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
12-14 16:35:18.439 17489-19295/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
12-14 16:35:18.439 17489-19295/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 16:35:18.439 17489-19295/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 16:35:18.439 17489-19295/pl.librus.client W/System.err:     at java.lang.Thread.run(Thread.java:833)
12-14 16:35:21.715 17489-19286/pl.librus.client I/OkHttpClient: Callback failure for call to https://api.librus.pl/...
                                                                java.net.SocketTimeoutException: timeout
                                                                    at okio.Okio$3.newTimeoutException(Okio.java:207)
                                                                    at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                                    at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                    at okio.RealBufferedSource.read(RealBufferedSource.java:50)
                                                                    at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:439)
                                                                    at okio.Buffer.writeAll(Buffer.java:956)
                                                                    at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
                                                                    at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:57)
                                                                    at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
                                                                    at pl.librus.client.api.APIClient$2.onResponse(APIClient.java:122)
                                                                    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:833)
12-14 16:35:21.715 17489-19300/pl.librus.client I/OkHttpClient: Callback failure for call to https://api.librus.pl/...
                                                                java.net.SocketTimeoutException: timeout
                                                                    at okio.Okio$3.newTimeoutException(Okio.java:207)
                                                                    at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                                    at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                    at okio.RealBufferedSource.read(RealBufferedSource.java:50)
                                                                    at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:439)
                                                                    at okio.Buffer.writeAll(Buffer.java:956)
                                                                    at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
                                                                    at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:57)
                                                                    at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
                                                                    at pl.librus.client.api.APIClient$2.onResponse(APIClient.java:122)
                                                                    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:833)
12-14 16:35:21.720 17489-19568/pl.librus.client I/OkHttpClient: Callback failure for call to https://api.librus.pl/...
                                                                java.net.SocketTimeoutException: timeout
                                                                    at okio.Okio$3.newTimeoutException(Okio.java:207)
                                                                    at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
                                                                    at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
                                                                    at okio.RealBufferedSource.read(RealBufferedSource.java:50)
                                                                    at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:439)
                                                                    at okio.Buffer.writeAll(Buffer.java:956)
                                                                    at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
                                                                    at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:57)
                                                                    at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
                                                                    at pl.librus.client.api.APIClient$2.onResponse(APIClient.java:122)
                                                                    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                    at java.lang.Thread.run(Thread.java:833)
12-14 16:35:30.368 17489-19293/pl.librus.client W/System.err: java.net.SocketTimeoutException: timeout
12-14 16:35:30.370 17489-19293/pl.librus.client W/System.err:     at okio.Okio$3.newTimeoutException(Okio.java:207)
12-14 16:35:30.370 17489-19293/pl.librus.client W/System.err:     at okio.AsyncTimeout.exit(AsyncTimeout.java:250)
12-14 16:35:30.370 17489-19293/pl.librus.client W/System.err:     at okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
12-14 16:35:30.370 17489-19293/pl.librus.client W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
12-14 16:35:30.371 17489-19293/pl.librus.client W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
12-14 16:35:30.371 17489-19293/pl.librus.client W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
12-14 16:35:30.371 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
12-14 16:35:30.371 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
12-14 16:35:30.371 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
12-14 16:35:30.371 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
12-14 16:35:30.372 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
12-14 16:35:30.372 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
12-14 16:35:30.372 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:287)
12-14 16:35:30.372 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
12-14 16:35:30.372 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12-14 16:35:30.372 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.Call.access$100(Call.java:35)
12-14 16:35:30.373 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
12-14 16:35:30.373 17489-19293/pl.librus.client W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
12-14 16:35:30.373 17489-19293/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-14 16:35:30.373 17489-19293/pl.librus.client W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-14 16:35:30.373 17489-19293/pl.librus.client W/System.err:     at java.lang.Thread.run(Thread.java:833)
`

**Comment by xdk78** [comment]
Tested on https://github.com/xdk78/librus-client/commit/22d939e57354daad19309388b1460aa6604eba1a
