### ISSUE TITLE
Better data loading and offline support.

### ISSUE THREAD

**Issue by shymmq** [shymmq/librus-client#68]
Update data in particular fragments instead of MainActivity; only update elements that change frequently; handle no internet connection properly; make additional requests for grade categories, comments etc.

**Comment by shymmq** [comment]
Maybe we should restore the splashscreen as well?

**Comment by xdk78** [comment]
Why not, If you have any idea show us.

**Comment by Frioo** [comment]
Splashscreen was a nice feature in my opinion.

**Comment by rowysock** [comment]
Fixed by 4ea54718c23df462778aed7824872ed2b98ddbce
