### ISSUE TITLE
Make notifications great again!

### ISSUE THREAD

**Issue by shymmq** [shymmq/librus-client#69]

**Comment by kacpi2442** [comment]
( ͡° ͜ʖ ͡°)
![image](https://cloud.githubusercontent.com/assets/20999816/22805991/3871f3ec-ef20-11e6-9491-32a1bfba019e.png)

**Comment by shymmq** [comment]
Needs layout & backend testing.

**Comment by rowysock** [comment]
layout tests added to dev mode in 3edea78b38012336439a9c432109b5fa6b280c1c
