### ISSUE TITLE
Make app compliant with F-Droid policy

### ISSUE THREAD

**Issue by mimi89999** [shymmq/librus-client#73]
It would be nice to have this app in F-Droid. However, to be added, the app needs to be 100% free (including dependencies). I noticed the non-free `com.google.gms` library as a requirement. If it could be removed, it would be great.

**Comment by xdk78** [comment]
Google GMS is used to making app better:
- logs
- analytics 
- notifications
@shymmq he is leader and he knows much more.

**Comment by shymmq** [comment]
@mimi89999 ,
unfortunately, this would mean removing real-time notifications which are one of the core components of our app

**Comment by mimi89999** [comment]
There could be 2 variants of this app: one free for F-Droid and one with notifications.

**Comment by mimi89999** [comment]
I can make 2 productFlavors. How to call them?

**Comment by mimi89999** [comment]
Ah, the foreign repo `https://oss.sonatype.org/content/repositories/snapshots/` also has to be removed. That isn't a problem since `eu.davidea:flexible-adapter:5.0.0-rc1` is also in the standard repo.

**Comment by mimi89999** [comment]
But is needed for `org.immutables:value:2.4.4-SNAPSHOT` :P

**Comment by shymmq** [comment]
@rowysock ?

**Comment by rowysock** [comment]
We need immutables in version 2.4.4 because of this issue: https://github.com/immutables/immutables/issues/117. Maybe let's just wiat for the next immutables relese and then we could remove https://oss.sonatype.org/content/repositories/snapshots/ ?

**Comment by mimi89999** [comment]
@rowysock Isn't it immutables/immutables#546

**Comment by rowysock** [comment]
@mimi89999 Yes, actually it is

**Comment by mimi89999** [comment]
@shymmq please git tag all future releases with the same label as the app version name. It will allow F-Droid to automatically detect updates.
