### ISSUE TITLE
Wrong number of grades

### ISSUE THREAD

**Issue by mimi89999** [shymmq/librus-client#91]
When I open the grades fragment, the number of grades in each category (subject) is correct.
When I collapse a category (subjects) to see grades, the number of grades below the category name (subject) changes the value to 5 oO.

I think it is the *last* value that number of grades had when building the fragment.

Anyway, I will further investigate that issue tomorrow.

**Comment by shymmq** [comment]
5 is probably used somewhere in layout as a placeholder.

**Comment by shymmq** [comment]
@mimi89999 It works for me, I think it might be related to #87
