### ISSUE TITLE
Long subject title displayed incorrectly in GradesFragment

### ISSUE THREAD

**Issue by shymmq** [shymmq/librus-client#94]

**Comment by Frioo** [comment]
Everything seems fine.

**Comment by rowysock** [comment]
Unfortunately it still doesn't. 4th lesson title should be trimmed with ellipsis. "Projektowanie i obsługa projektów..."
![screenshot_20170225-125518](https://cloud.githubusercontent.com/assets/2960605/23330880/16aac026-fb5b-11e6-9590-a0fa9f83fbd3.png)

**Comment by shymmq** [comment]
I will also change subject names to something more reasonable in order to resolve #97
