### ISSUE TITLE
Add more info fileds in settings 

### ISSUE THREAD

**Issue by xdk78** [shymmq/librus-client#96]
Just add fields like:
- App version 
- Authors 
- library licenses

**Comment by shymmq** [comment]
Good idea.

**Comment by xdk78** [comment]
https://github.com/mikepenz/AboutLibraries

**Comment by Frioo** [comment]
Wouldn't it be better to create a separate sticky 'About' item in the drawer?

**Comment by shymmq** [comment]
Also remove `useTabs` entry which is now unused.

**Comment by shymmq** [comment]
@Frioo we should avoid adding too many items because on many smaller devices the drawer items alredy take up most of the vertical space. On Moto G, only about 8 items fit without scrolling and we already have 6 (4 fragments, lucky number and settings)

**Comment by shymmq** [comment]
Fixed in 4e9f6d4af382ea226f2826426504a6af16ffeaeb
