### ISSUE TITLE
'load more' button is too low

### ISSUE THREAD

**Issue by Frioo** [shymmq/librus-client#99]
OnePlus 3@Sultan's CM13 (6.0.1)
![screenshot_20170225-123939](https://cloud.githubusercontent.com/assets/22414778/23330789/a11609ae-fb57-11e6-9666-f73c8a63ebf2.png)

**Comment by shymmq** [comment]
It's not a bug, it's how scrollable  footers in FlexibleAdapter work.

**Comment by Frioo** [comment]
So it's not possible to remove the blank space surrounding it?

**Comment by mimi89999** [comment]
I like the fact that there is some space surrounding it and not last lesson, show more and bottom of the screen.

**Comment by shymmq** [comment]
I also think that it being fullscreen is a good thing. It provides a clear message, so the user will not think that there was an error while loading data or something.
